# Generated by Django 5.2.3 on 2025-07-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='message',
            new_name='messages',
        ),
    ]
