# Generated by Django 5.2.3 on 2025-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_message_contacts_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='messages',
            new_name='message',
        ),
    ]
